Allow cluster create with no security groups
Got an unbound variable error without this fix:
  UnboundLocalError: local variable 'sec_groups'
  referenced before assignment

This appears to have been caused by the move to use the neutron client
in the following commit:
b4fb2c404c371a5ba9b28a3ac769c94e69b8c141

Co-Authored-By: Jeremy Freudberg <jeremyfreudberg@gmail.com>
Closes-Bug: #1718940
Change-Id: I4f0b5a6b27ee2fb7821ec42faba3a69ce5a4bb78