Fix syntax error in image widths
I get when building sahara this error:

  File "/usr/lib/python3.6/site-packages/sphinx/writers/html5.py", line 548, in visit_image
     atts['width'] = int(atts['width']) * scale
  ValueError: invalid literal for int() with base 10: '800px'

As it turns out, the default is pixels anyway, so we don't need to add a
type suffix. For scale to work, we need to specify both width and height
for images, otherwise sphinx reports an error.

Change-Id: If0f8383e37a8b1185a8a08b24c79b313fdcb498c