Resolves issue where to allow custom repo URLS
Using an centos7 image and changing the HDP and HDP-UTILS URL location
resulted in an error of
"os_type=os_type_map[client.get_host_info[ambari.fqdn())["os_type"]]
KeyError: u'centos7'. This results in only being able to change the
HDP and HDP-UTILS URL if you were using centos6 or redhat6.This change
adds centos7 and redhat7 to the map to allow custom HDP and HDP-UTILS URLs.

Should we add additional operating systems to the list?

Closes-Bug: #1599252

Change-Id: Iaa5cd773c5daeabeda287048a2d3f8696faa1436
(cherry picked from commit d067680e68f97b47665bbd9ece2dd810c254385a)