Added missing lib to dev UI installation guide
Horizon doesn't start without this lib.
Error: "ffi.h: No such file or directory"

Change-Id: I02261adbc73b627fd49e152d2de8e9a1c9a3ba95