[IT] Fixed error when skipping scaling test
If flag "SKIP_SCALING_TEST" is set to "True" in config file of integration
tests, the error occurs and trace is the following:

Traceback (most recent call last):
  File "/home/ylobankov/Sahara/master1/sahara/sahara/tests/integration/tests/gating/test_vanilla_gating.py", line 383, in test_vanilla_plugin_gating
    self.print_error_log(message, e)
  File "sahara/openstack/common/excutils.py", line 68, in __exit__
    six.reraise(self.type_, self.value, self.tb)
  File "/home/ylobankov/Sahara/master1/sahara/sahara/tests/integration/tests/gating/test_vanilla_gating.py", line 375, in test_vanilla_plugin_gating
    new_cluster_info['node_info'], self.vanilla_config)
TypeError: 'NoneType' object has no attribute '__getitem__'.

This CR fixes that.

Closes-bug: #1308555

Change-Id: I84a3de535e2500dccb776c2483dcd725bb0a310c